# Generated by Django 3.2.12 on 2024-10-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lego_rewards_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('budget', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('piece_count', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.IntegerField()),
                ('theme_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField()),
                ('review_text', models.CharField(max_length=1500)),
                ('rating', models.IntegerField()),
                ('lego_rewards_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.legoset')),
            ],
        ),
        migrations.AddField(
            model_name='legoset',
            name='theme_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.theme'),
        ),
        migrations.AddField(
            model_name='customer',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.legoset'),
        ),
    ]
