# Generated by Django 3.2.12 on 2024-10-28 22:21

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Theme = apps.get_model('myapp', 'Theme')
    LegoSet = apps.get_model('myapp', 'LegoSet')
    Customer = apps.get_model('myapp', 'Customer')
    Reviews = apps.get_model('myapp', 'Reviews')

    # Add initial themes
    theme1 = Theme.objects.create(theme_id=1, theme_name='Star Wars')
    theme2 = Theme.objects.create(theme_id=2, theme_name='Harry Potter')
    theme3 = Theme.objects.create(theme_id=3, theme_name='Technic')

    # Add initial Lego sets
    set1 = LegoSet.objects.create(set_id=1, name='Millennium Falcon', piece_count=7541, price=799.99, theme_id=theme1, status='available')
    set2 = LegoSet.objects.create(set_id=2, name='Hogwarts Castle', piece_count=6020, price=399.99, theme_id=theme2, status='available')
    set3 = LegoSet.objects.create(set_id=3, name='Bugatti Chiron', piece_count=3599, price=349.99, theme_id=theme3, status='retired')

    # Add initial customers
    customer1 = Customer.objects.create(lego_rewards_id=1, name='John Doe', set_id=set1, budget=1000.00)
    customer2 = Customer.objects.create(lego_rewards_id=2, name='Jane Smith', set_id=set2, budget=500.00)
    customer3 = Customer.objects.create(lego_rewards_id=3, name='Alice Johnson', set_id=set3, budget=400.00)

    # Add initial reviews
    Reviews.objects.create(review_id=1, set_id=set1, lego_rewards_id=customer1, review_text='Amazing set with great detail!', rating=5)
    Reviews.objects.create(review_id=2, set_id=set2, lego_rewards_id=customer2, review_text='Magical experience building this set.', rating=4)
    Reviews.objects.create(review_id=3, set_id=set3, lego_rewards_id=customer3, review_text='Challenging build, but worth it!', rating=5)

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
